access_afs: added another klist output parsing version
On the NAF since 2021-09-01 we observe a completely different format:
Sep 2 12:31:34 2021
This leads to
```
2021-09-01 15:47:28 - exception:CRITICAL - Exception occured in grid-control [git (deca70b)]

AccessTokenError: Unable to parse kerberos ticket information!
----------
ValueError: time data 'Sep 2 12:31:34 2021' does not match format '%m %d %Y %H:%M:%S'
```